#Use of this page is optional. If you use code here, make sure either import page2 or from page2 import * appear on your main.py page.

Noun1 = input("Enter a noun: ")
place = input("Enter a place: ")
Adj1 = input("Enter an adjective: ")
Noun2 = input("Enter a noun: ")
Adj2 = input("Enter another adjective: ")
Noun3 = input("Enter another noun: ")
Noun4 = input("Enter another noun: ")
Noun5 = input("Enter a plural noun: ")
number = input("Enter an integer: ")
Adj3 = input("Enter an adjective: ")
Adj4 = input("Enter another adjective: ")
name = input("Enter a name: ")
sentence1 = (place + ' smelt of ' + Noun1 + ' and ' + Adj1 + ' ' + Noun2 + '. ')
sentence2 = ('At one end of it a ' + Adj2 + ' poster, too large for indoor display, had been tacked to the ' + Noun3 + '. ') 
sentence3 = ('It depicted simply a '+ Adj3 + ' ' + Noun4 + ' , more than a metre wide,  and the face of ' + name + ' who was about ' + number + ' years old, with heavy black ' + Noun5 + ' and ruggedly ' + Adj4 + ' features. ')
sentence4 = ('BIG BROTHER IS WATCHING YOU, the caption beneath it ran.')
print(sentence1 + sentence2 + sentence3 + sentence4)