#Use of this page is optional. If you use code here, make sure either import page1 or from page1 import * appear on your main.py page.

Adj1 = input("Enter an adjective: ")
Adj2 = input("Enter another adjective: ")
Adj3 = input("Enter another adjective: ")
Noun1 = input("Enter a plural noun: ")
Noun2 = input("Enter another noun: ")
Noun3 = input("Enter another noun: ")
Noun4 = input("Enter another noun: ")
Drink = input("Enter a beverage: ")
name = input("Enter a name: ")
name2 = input("Enter another name: ")
verb1 = input("Enter a verb in past tense: ")
verb2 = input("Enter another verb in past tense: ")
verb3 = input("Enter another verb in the present tense: ")
adverb = input("Enter an adverb: ")
Sentence1 = ('All ' + Adj1 + ' ' + Noun1 + ' are equal, but some ' + Adj1 + ' ' + Noun1 + ' are more equal than others. ')
Sentence2 = (name +', of the Manor Farm, had ' + verb2 + ' the ' + Noun2 + ' for the night, but was too ' + Adj2 + ' to remember to '+ verb3 + ' the ' + Noun3 + '. ') 
Sentence3 = ('With the ring of light from his lantern dancing from side to side, he ' + adverb +' '+ verb1 + ' the ' + Noun4 + ' across the yard, kicked off his ' + Adj3 + ' boots at the back door, poured himself a last glass of ' + Drink + ' from the barrel in the scullery, and made his way up to bed, where ' + name2 + ' was already snoring.')
print(Sentence1 + Sentence2 + Sentence3)